Makefile
versions.json

Currently, 4-2-stable doesn't include all the packages needed to build irods 4.2.7, because the 4.2.7 unit tests depend on catch2, which is not in 4-2-stable. catch2 is in master, so cherry-pick it across, and also add it to the list of server externals which was added in 9ccf28b and 10c80b8, after catch2 was added

cherry-pick 89af3e4 because 4.2.7 doesn't build without catch2

---

Makefile
install_prerequisites.py
versions.json

Builds successfully on ubuntu:16.04 and centos:7 images after installing git (for cloning), sudo, python, and curl. Still running tests with iRODS server and plugins built against these externals.

[#34] Bump externals for 4-2-stable

---

versions.json

Testing that it works with dependent plugin...

[#39] Copy files from lib64 for qpid-with-proton RPM (master)

---

install_prerequisites.py

gpg could alternatively be configured to disable ipv6
(see https://github.com/f-secure-foundry/usbarmory-debian-base_image/issues/9#issuecomment-451635505)
```
RUN mkdir ~/.gnupg && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf
```

[36] use the ipv4 pool for gpg keyservers (4-2-stable)

---

versions.json

Tested on Ubuntu 16 and Centos 7.

[#73] Made spdlog the top-level directory on installation (master)

---

versions.json

tested manually and passed via indexing plugin training, on 4-2-stable

[irods/externals76] remove lib64 for elasticlient, bump build number

---

Makefile
build.py
install_prerequisites.py
versions.json

Hi,
prompted by discussion at https://github.com/irods/irods/issues/5082 I attempted to follow
https://docs.irods.org/4.2.8/getting_started/installation/#non-package-install-run-in-place
to perform a build that does not use fpm. I discovered that the build scripts still try to install
fpm and related ruby packages (even though they are not used). This somewhat defeats the
purpose of doing the build in this manner. This branch contains some small changes to remove 
these dependencies in the case of this type of build.
The install procedure changes from:
```
user@hostname:/tmp/irods-externals $ ./install_prerequisites.py
user@hostname:/tmp/irods-externals $ make
```
to:
```
user@hostname:/tmp/irods-externals $ ./install_prerequisites.py -n
user@hostname:/tmp/irods-externals $ make …
```

Build without installing fpm.

---

build.py
install_prerequisites.py

using rvm version as well as ruby version means that ruby version needs updating every time rvm add a new entry to the 2.6 stream. This is currently failing, because 2.6.6 gets installed, but 2.6.5 is looked for. rvm can take the patch version, and if we supply it then this problem won't recur when rvm add 2.6.7

resolve issue with rvm version mismatch resulting in gem: command not found

---

install_prerequisites.py

https://sks-keyservers.net/status/ has
```
This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.
Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all.
```

retrieve keys from rvm.io via curl (4-2-stable)

---

install_prerequisites.py

https://sks-keyservers.net/status/ has
```
This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.
Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all.
```

retrieve keys from rvm.io via curl (master)

---

versions.json

Necessary for indexing plugin to work, since: https://github.com/irods/irods_capability_indexing/commit/1bada02b0492f7f8da699bda
(Otherwise dependencies in elasticlient were not loading.)
See https://github.com/irods/irods/issues/5860 for history.

Use DF_ORIGIN flag to locate other libraries (4-2-stable)

---

versions.json

Additionally, pass --parallel to configure.
This will require that https://github.com/irods/CMake pull new tags from upstream
I haven't yet tested that this works on anything beyond my personal rig, due to our fork not having the `v3.21.4` tag.

[irods/irods#5669] Bump CMake to 3.21.4

---

Makefile
README.md
build.py
install_prerequisites.py
versions.json

This PR adds support for building only the externals packages needed for compiling the iRODS server.
This PR needs to be tested to make sure CentOS 7, AlmaLinux 8, and Rocky Linux 8 support is still functional.

Ubuntu 20.04 / Python 3 / Version bumps

---

versions.json

Patches pulled:
- boostorg/boost_install#52 - set `CMP0057` in cmake config
- boostorg/boost_install#53 - fix Python 3.10+ compatibility

[146, irods/irods_5669] Pull upstream patches into boost build

---

Makefile
build.py
versions.json

This PR accomplishes a few things:
- Puts CMake configuration files in the spdlog, catch2, and cppzmq packages
- Puts catch2's headers in the right place
- Removes the extra copy of fmt from spdlog

[141, 142, 143, 144, irods/irods_5669, irods/irods_6086] Build spdlog, catch2, and cppzmq with cmake

---

versions.json

Updated build instructions so that fmt is compiled against the C++17 standard.

[#152] Bumped fmt version (main)

---

versions.json

Addresses irods/irods_resource_plugin_s3#2092
Cherry-picked from https://github.com/irods/externals/pull/180
libs3 needs to be bumped to the latest commit on the master branch in order for the main branch to build for the iRODS S3 resource plugin.

[irods/irods_resource_plugin_s3#2092] Bump libs3 (4-2-stable)

---

Makefile
build.py
versions.json

\- Remove autoconf external as it is no longer used.
\- Bump required ruby version to 3.1.2 because there is no package for
the previous version available for Ubuntu 22.04 so we need to bump this
version in order to build externals for this platform.
\- Bump SHAs for the following externals in order to prevent build errors
caused by deprecation warnings due to using old OpenSSL types and
functionality:
aws-sdk-cpp
libs3
qpid-proton
Ubuntu 22.04 uses OpenSSL 3.0 and the build processes for these
externals are compatible with 1.1.0.
---
Still trying on other platforms and messing with minimum bumps and whatnot, but this worked for building externals which can build iRODS packages which run in the testing environment.
Sibling PRs:
https://github.com/irods/aws-sdk-cpp/pull/1 …

[#177] Add support for building on Ubuntu 22.04 (main)

---

Makefile
versions.json

We only use imagemagick in the training repo, but we don't use the externals package. Let's get rid of it.

[#200] Remove imagemagick

---

Makefile
versions.json

Addresses #206
irods_client_rest_cpp is now deprecated and archived, so pistache is no longer needed or desired.

[#206] Remove pistache

---

versions.json

Addresses irods/libs3#24
Cherry-picked from #183 
I haven't tested this yet. Will await confirmation from @JustinKyleJames

[irods/libs3#24] Referring to the new libs3 library. (4-2-stable)

---

build.py
install_prerequisites.py
versions.json

Addresses #232
Addresses #234
Addresses irods/irods_rule_engine_plugin_audit_amqp#137

[#232,#234,irods/irods_rule_engine_plugin_audit_amqp#137] fix -libcxx `RUNPATH` values, also add missing comma to `install_prerequisites.py`

---

patches/clang/1006-clang-tools-extra-py-fix-invalid-escape-sequences.patch
patches/clang/1007-opt-viewer-fix-invalid-escape-sequence.patch
versions.json

Addresses #260
Not yet tested, so PR is in draft mode

[#260] Fix invalid escape sequences in clang package's python files
