- versions.json
Testing that it works with dependent plugin...
> [#39] Copy files from lib64 for qpid-with-proton RPM (4-2-stable)

- build.py
- install_prerequisites.py
and use it for the gpg keyservers request
> [50] add retries option to run_cmd

- build.py
- install_prerequisites.py
and use it for the gpg keyservers request
> [#50] add retries option to run_cmd

- build.py
- install_prerequisites.py
Test builds of externals successful on Centos 7, and Ubuntu 16 and 18.
(Yet to be done for SuSE ,Debian, OSX) .
> RVM and ruby parameterized to specific versions (4-2-stable)

- build.py
- install_prerequisites.py
Cherry pick of changes from 4-2-stable
Issue: https://github.com/irods/externals/issues/62
Not yet fully tested on master
> Parameterize ruby & rvm versions (master)

- Makefile
- build.py
- install_prerequisites.py
- versions.json
now builds cpr and elasticlient, prerequisites for building the indexing plugin
> Cpr elasticlient master

- install_prerequisites.py
gpg could alternately be configured to disable ipv6
> [#36] use the ipv4 pool for gpg keyservers (master)

- irods_consortium_continuous_integration_build_hook.py
cherry-picked from 76b954a6515c882c706b0d760846ace0bf98e04e
For #78. Packages built successfully from CI job.
> cherry-pick build hook to master

- build.py
- install_prerequisites.py
- versions.json
Addressing #87 .
Still in process of testing for 4-2-stable, this one will follow . Will advise when ready to merge.
> Change to QPID library RUNPATHs (master)

- README.md
- build.py
- install_prerequisites.py
- versions.json
Requires a new release of mungefs irods-external package.
> [#132] Added support for AlmaLinux 8 (main)

- versions.json
Partially addresses irods/irods_resource_plugin_s3#2092
> [irods/irods_resource_plugin_s3#2092] Bump libs3 (main)

- versions.json
Addresses https://github.com/irods/irods_resource_plugin_s3/issues/2092
See comment thread: https://github.com/irods/externals/pull/181#discussion_r1104454347
> [irods/irods_resource_plugin_s3#2092] libs3: shave the sha (main)

- Makefile
- build.py
- versions.json
We are removing elasticlient and CPR for the reasons detailed here: irods/irods_capability_indexing#128
Once I've confirmed everything still builds just fine, I'll mark as ready for review.
> [irods/irods_capability_indexing#128] Remove elasticlient and CPR

- Makefile
- build.py
- versions.json
> [#196] Remove jansson

- versions.json
Will verify externals build for each OS shortly.
> [irods/irods#7247] Bumped Boost library to 1.81 (main)

- Makefile
- build.py
- versions.json
> [#195] Add jwt-cpp

- Makefile
- build.py
- versions.json
In service of irods/irods_resource_plugin_s3#2138
> [irods/irods_resource_plugin_s3#2138] remove libs3

- build.py
> [#225] Pass package revisions to fpm via --iteration

- Makefile
- versions.json
> [#228] Remove aws-sdk-cpp

- Makefile
- versions.json
> [#257] Add jsoncons package
